const students = Array.from({length:37},(_,i)=>`دانش‌آموز ${new Intl.NumberFormat('fa-IR').format(i+1)}`);
const state = {student:null, image:null, results:JSON.parse(localStorage.getItem('tashihyar_results')||'{}')};
const $=s=>document.querySelector(s);
const studentGrid=$('#studentGrid');
students.forEach((name,i)=>{const b=document.createElement('button');b.className='student-btn';b.type='button';b.textContent=name;b.onclick=()=>selectStudent(i);studentGrid.appendChild(b)});
function selectStudent(i){state.student=i;document.querySelectorAll('.student-btn').forEach((b,n)=>b.classList.toggle('active',n===i));$('#selectedStudent').textContent=`انتخاب شد: ${students[i]}`;refreshButton()}
function refreshButton(){ $('#checkBtn').disabled=!(state.student!==null&&state.image); }
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const max=1800;const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=url})}
$('#homeworkImage').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{state.image=await compressImage(f);$('#preview').src=state.image;$('#previewWrap').classList.remove('hidden');refreshButton()}catch{alert('خواندن تصویر ممکن نشد. دوباره تلاش کن.')}};
$('#removeImage').onclick=()=>{$('#homeworkImage').value='';state.image=null;$('#previewWrap').classList.add('hidden');refreshButton()};
$('#checkBtn').onclick=checkHomework;
async function checkHomework(){
  $('#progressPanel').classList.remove('hidden');$('#resultPanel').classList.add('hidden');$('#checkBtn').disabled=true;$('#progressText').textContent='دستخط و پاسخ‌های روی صفحه در حال تحلیل هستند…';
  const payload={studentName:students[state.student],taskTitle:$('#taskTitle').value.trim()||'تکلیف',rubric:$('#rubric').value.trim(),image:state.image};
  try{const res=await fetch('/api/check-homework',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||'خطا در بررسی');showResult(data);state.results[state.student]={...data,checkedAt:new Date().toISOString()};localStorage.setItem('tashihyar_results',JSON.stringify(state.results));renderDashboard()}catch(err){alert(err.message||'خطای نامشخص');}finally{$('#progressPanel').classList.add('hidden');refreshButton()}
}
function showResult(d){$('#resultPanel').classList.remove('hidden');$('#resultTitle').textContent=d.studentName||students[state.student];const status=d.overallStatus||'review';const badge=$('#resultStatus');badge.className='status-badge '+(status==='good'?'status-good':status==='bad'?'status-bad':'status-review');badge.textContent=status==='good'?'مناسب':status==='bad'?'نیازمند اصلاح':'نیازمند بررسی';const a=d.answers||[];const good=a.filter(x=>x.status==='correct').length,bad=a.filter(x=>x.status==='incorrect'||x.status==='incomplete').length,rev=a.filter(x=>x.status==='review').length;$('#resultSummary').innerHTML=`<div class="summary-box"><strong>${good}</strong><span>درست</span></div><div class="summary-box"><strong>${rev}</strong><span>مشکوک</span></div><div class="summary-box"><strong>${bad}</strong><span>غلط/ناقص</span></div>`;$('#answersList').innerHTML=a.length?a.map((x,i)=>{const c=x.status==='correct'?'good':x.status==='review'?'review':'bad';const t=x.status==='correct'?'درست':x.status==='review'?'بررسی معلم':'نیازمند اصلاح';return `<div class="answer-item ${c}"><div class="answer-top"><span class="answer-label">${escapeHtml(x.question||`بخش ${i+1}`)}</span><span class="answer-state">${t} · ${Math.round((x.confidence||0)*100)}٪</span></div><div class="answer-text">${escapeHtml(x.feedback||'بدون توضیح')}</div></div>`}).join(''):'<div class="answer-item review"><div class="answer-text">مدل نتوانست پاسخ‌ها را به‌صورت تفکیک‌شده تشخیص دهد. تصویر را بررسی کن و دوباره امتحان کن.</div></div>';$('#teacherNote').textContent=d.teacherNote||'نتیجه را قبل از ثبت نهایی با نمونه تکلیف مقایسه کن.'}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function renderDashboard(){const vals=Object.values(state.results);const checked=vals.length,review=vals.filter(x=>x.overallStatus==='review').length,bad=vals.filter(x=>x.overallStatus==='bad').length;$('#checkedCount').textContent=new Intl.NumberFormat('fa-IR').format(checked);$('#dashChecked').textContent=new Intl.NumberFormat('fa-IR').format(checked);$('#dashReview').textContent=new Intl.NumberFormat('fa-IR').format(review);$('#dashIncomplete').textContent=new Intl.NumberFormat('fa-IR').format(bad);$('#resultsTable').innerHTML=vals.length?vals.map(x=>{const i=students.indexOf(x.studentName),c=x.overallStatus==='good'?'good':x.overallStatus==='bad'?'bad':'review';return `<div class="row"><span><i class="dot ${c}"></i>${escapeHtml(x.studentName)}</span><span>${c==='good'?'مناسب':c==='bad'?'نیازمند اصلاح':'بررسی معلم'}</span></div>`}).join(''):'<div class="selected-student">هنوز نتیجه‌ای ثبت نشده است.</div>'}
$('#clearResults').onclick=()=>{if(confirm('نتایج ذخیره‌شده روی این گوشی پاک شود؟')){state.results={};localStorage.removeItem('tashihyar_results');renderDashboard()}};
renderDashboard();
